services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - taskflow-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - BACKEND_PORT=3001
      - REDIS_HOST=cache
      - REDIS_PORT=6379
    networks:
      - taskflow-network
    depends_on:
      - cache
    restart: on-failure

  cache:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - taskflow-network

volumes:
  redis_data:

networks:
  taskflow-network:
    driver: bridge